apiVersion: v2
name: secrets-operator-issue
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: vault-secrets-operator 
    version: 0.1.0
    repository: https://helm.releases.hashicorp.com
